### ISSUE TITLE
Truncate by words

### ISSUE THREAD

**Issue by Fatih90** [imcvampire/vue-truncate-filter#1]
great filter, but what about truncating by words ?

for example

this text

`Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt`

truncated
`Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in...`

becomes

`Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...`

**Comment by imcvampire** [comment]
I think I already added it to the latest version. But if you're using latest version and it doesn't work like expected, I think it's a but.

**Comment by Fatih90** [comment]
@imcvampire omg sorry it's working great, i was using another function to truncate my text, 😋

**Comment by imcvampire** [comment]
@Fatih90 Thanks for using my filter :+1: . I will close this issue :)
