### ISSUE TITLE
Doesn't work with Chinese

### ISSUE THREAD

**Issue by 1c7** [imcvampire/vue-truncate-filter#12]
## Example
![111](https://user-images.githubusercontent.com/1804755/42370032-452b487a-813e-11e8-9e4f-163a28132716.jpg)
![222](https://user-images.githubusercontent.com/1804755/42370033-45804f14-813e-11e8-8716-bbc4ccc4b410.jpg)
![333](https://user-images.githubusercontent.com/1804755/42370035-45eef374-813e-11e8-9655-31c8367f51aa.jpg)

## Issue
clearly it's implement by `split(' ')`
split by empty space
doesn't work with Chinese

## So
This is more of a  "just letting you know", not asking you to change it.

Still thanks you for build this.

**Comment by imcvampire** [comment]
Do you have any idea how to handle mandarin characters?

**Comment by 1c7** [comment]
@imcvampire I just wrote this, it work well

```javascript
Vue.filter('truncate', function (value, length) {
  if (!value) return ''
  value = value.toString()
  if(value.length > length){
    return value.substring(0, length) + "..."
  }else{
    return value
  }
})
```

**Comment by 1c7** [comment]
you can close this issue anytime

**Comment by 1c7** [comment]
😄

**Comment by 1c7** [comment]
I think I should just close it
