### ISSUE TITLE
Upgrade documentation for Vue 2.x

### ISSUE THREAD

**Issue by arielcamus** [imcvampire/vue-truncate-filter#2]
The syntax for filters with multiple arguments has changed to `{{ variable | truncate(100) }}`

**Comment by imcvampire** [comment]
Sorry for late response!

Can you help me to create PR to update documentation for Vue 2.x. Sorry because right now, I'm too busy :'(

**Comment by arielcamus** [comment]
There you go:
https://github.com/imcvampire/vue-truncate-filter/pull/4

**Comment by imcvampire** [comment]
Merged! Many thanks :)
