### ISSUE TITLE
how use with v-html?

### ISSUE THREAD

**Issue by andysay** [imcvampire/vue-truncate-filter#9]
Hi author !  how use with v-html? 

 v-html="message.content ||  truncate(50) "> not work, thanks!

**Comment by imcvampire** [comment]
Have you try `v-html="message.content | truncate(50)"` (only 1 `|`)?

**Comment by andysay** [comment]
yeah, i'm try , but not work ;(

**Comment by pexea12** [comment]
You cannot use `vue-truncate-filter` with `v-html`: [https://github.com/vuejs/vue/issues/4352#issuecomment-263976170](https://github.com/vuejs/vue/issues/4352#issuecomment-263976170)

You can truncate your message before putting in `v-html` via:
`this.$options.filters.truncate(message.content, 50)`

**Comment by kakulukia** [comment]
Why this inconsistency where i can use filter in bindings (https://vuejs.org/v2/guide/filters.html#ad) but am not able to use it in v-html or v-text?

**Comment by imcvampire** [comment]
You can read about it https://vuejs.org/v2/guide/migration.html#Filters-Outside-Text-Interpolations-removed

**Comment by kakulukia** [comment]
okay, got it .. but why is the old/removed filter syntax still inside the docs (see the link i posted above)?

thx for answering!

**Comment by imcvampire** [comment]
@kakulukia It still there, but do not apply to v-html anymore!

**Comment by kakulukia** [comment]
its very sad, tho :/
